# Generated by Django 5.1 on 2024-08-19 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_content_images/')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='blog.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
