# Generated by Django 5.1 on 2024-08-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Nowość'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='Na czasie'),
        ),
    ]
