# Generated by Django 5.1 on 2024-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_is_new_blogpost_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
