# Generated by Django 5.1 on 2024-08-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogcategory_slug_blogpost_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
    ]
